# Generated by Django 4.2.30 on 2026-05-19 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='rating',
            field=models.FloatField(default=4.5),
        ),
    ]
