# Generated by Django 4.2.30 on 2026-05-19 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='portfolio',
            field=models.FileField(blank=True, null=True, upload_to='portfolio/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pricing',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='qualification',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='work_image',
            field=models.ImageField(blank=True, null=True, upload_to='work_images/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='work_video',
            field=models.FileField(blank=True, null=True, upload_to='work_videos/'),
        ),
    ]
