# Generated by Django 4.2.30 on 2026-05-22 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
